<?php
return [
    ['GET', '/', 'HomeController@index'],
    ['POST', '/', 'RecordController@record'],
    ['GET', '/', 'RecordController@record'],
    ['GET', '/register', 'AuthController@showRegisterForm'],
    ['POST', '/register', 'AuthController@register'],
    ['GET', '/login', 'AuthController@showLoginForm'],
    ['POST', '/login', 'AuthController@login'],
    ['GET', '/logout', 'AuthController@logout'],
    ['GET', '/reviews', 'ReviewsController@reviews'],
    ['POST', '/reviews', 'ReviewsController@add'],
    ['GET', '/contacts', 'ContactsController@Contacts'],
    ['POST', '/contacts', 'ContactsController@add'],
    ['GET', '/admin', 'AdminController@admin'],
    ['GET', '/admin/users', 'AdminUsersController@users'],
    ['GET', '/admin/users/edit/{id}', 'AdminUsersController@edit'],
    ['POST', '/admin/users/update/{id}', 'AdminUsersController@update'],
    ['POST', '/admin/users/delete/{id}', 'AdminUsersController@delete'],
    ['GET', '/account', 'AccountController@account'],
    ['POST', '/account', 'AccountController@account'],
    ['GET', '/about', 'AboutController@about'],
    ['GET', '/services', 'ServicesController@services'],
    ['GET', '/servicesdetail/{id}', 'ServicesdetailController@servicesdetail'],
    ['GET', '/record', 'RecordController@record'],
    ['POST', '/record', 'RecordController@record'],
    ['GET', '/redactEmail', 'RedactEmailController@redact'],
    ['POST', '/redactEmail', 'RedactEmailController@redact'],
    ['GET', '/admin/reviews', 'AdminReviewsController@adminReviews'],
    ['POST', '/admin/reviews/approve/{id}', 'AdminReviewsController@approve'],
    ['POST', '/admin/reviews/delete/{id}', 'AdminReviewsController@delete'],
];